spring:
  application:
    name: course-catalog-service
  springdoc:
      api-docs:
        enabled: true
#this is where you configure your datasource url and the type of SQL statements that are to run
  dataSource:
    url: jdbc:mysql://localhost:3306/spring_test
    username: root
    password: Asadul@54321
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update

#  dataSource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    show-sql : true
#
#  h2:
#    console:
#      enabled: true


message: Hello from default Profile
---
spring:
  config:
    activate:
      on-profile: prod
message: Hello from prod configruation
